ROOTDIR  =../../..
PKGNAME  =example
PROJNAME =plswigsimp

include $(ROOTDIR)/config.mk

#INCLUDES += -I$(INTERFACE_DIR)/otherpkg
#LIBS     += -L$(LIBPATHFLAG)yourlibpath  $(LIBFLAG)yourlibname$(LIBEND)

include $(SRCPUB_DIR)/swig/Makefile.plswig
