# Included by Makefile of plugin project integrated with swig.
# x3py framework: https://github.com/rhcad/x3py

SOURCES  =$(wildcard *.cpp)
OBJDIR   =._$(SWIG_TYPE)o/
OBJS     =$(addprefix $(OBJDIR), $(SOURCES:.cpp=$(OBJEXT)))

include $(SRCPUB_DIR)/swig/Makefile.swig

%.d: %.cpp
	$(DEPEND_CC) $@ $(INCLUDES) $<
$(OBJDIR)%$(OBJEXT): %.cpp
	-@test -d $(OBJDIR) || mkdir $(OBJDIR)
	$(CPP) $(CPPFLAGS) $(INCLUDES) -c $< -o $@

ifndef clean
include $(SOURCES:.cpp=.d)
endif
