ROOTDIR  =../../..
PKGNAME  =uidemo
PROJNAME =qtapp2
APPTYPE  =qtwin

include $(ROOTDIR)/config.mk

#INCLUDES += -I$(INTERFACE_DIR)/otherpkg
MOCS       = mainwnd.h

include $(SRCPUB_DIR)/mk/Makefile.qt4
